---
sudo: false

os: linux

language: go

go:
  - 1.13.x

install:
  - go mod download

before_script:
  - go version
  - export GOBIN="$GOPATH/bin"
  - go get golang.org/x/tools/cmd/goimports
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.16.0/install.sh | sh -s -- -b $(go env GOPATH)/bin && golangci-lint --version

script:
  - ./hack/go.sh ci-checks

deploy:
  - provider: script
    script: ./hack/go.sh ci-checks
    on:
      branch: master

